### ISSUE TITLE
Checking/unchecking only once OR incompatible with Gradle 7.0

### ISSUE THREAD

**Issue by romandr25** [react-native-community/react-native-checkbox#47]
Hey. I've installed the checkbox lib like it says in the README.md. 

- But checkboxes can change their visual state only on a first tap (for each). I even tried some checkbox code from your example. 

- Then I tried a manual installation and on `npx react-native run-android` got a failure:
(BTW later I 'uninstalled' the manual installation and it all went back to the first problem)

```
PS F:\Roma\prog\izigo> npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 970 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...

> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
31 actionable tasks: 9 executed, 22 up-to-date
F:\Roma\prog\izigo\android\app\src\main\java\com\izigo\MainApplication.java:39: error: method does not override or implement a method from a supertype
  @Override
  ^
F:\Roma\prog\izigo\android\app\src\main\java\com\izigo\MainApplication.java:42: error: cannot find symbol
      new MainReactPackage(),
          ^
  symbol:   class MainReactPackage
  location: class MainApplication
F:\Roma\prog\izigo\android\app\src\main\java\com\izigo\MainApplication.java:41: error: cannot find symbol
    return Arrays.asList(
           ^
  symbol:   variable Arrays
  location: class MainApplication
Note: F:\Roma\prog\izigo\android\app\src\debug\java\com\izigo\ReactNativeFlipper.java uses or overrides a deprecated
API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
F:\Roma\prog\izigo\android\app\src\main\java\com\izigo\MainApplication.java:39: error: method does not override or implement a method from a supertype
  @Override
  ^
F:\Roma\prog\izigo\android\app\src\main\java\com\izigo\MainApplication.java:42: error: cannot find symbol
      new MainReactPackage(),
          ^
  symbol:   class MainReactPackage
  location: class MainApplication
F:\Roma\prog\izigo\android\app\src\main\java\com\izigo\MainApplication.java:41: error: cannot find symbol
    return Arrays.asList(
           ^
  symbol:   variable Arrays
  location: class MainApplication
Note: F:\Roma\prog\izigo\android\app\src\debug\java\com\izigo\ReactNativeFlipper.java uses or overrides a deprecated
API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s

    at makeError (F:\Roma\prog\izigo\node_modules\execa\index.js:174:9)
    at F:\Roma\prog\izigo\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (F:\Roma\prog\izigo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (F:\Roma\prog\izigo\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)

```

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 612.26 MB / 3.59 GB
  Binaries:
    Node: 12.16.3 - F:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.4 - F:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: Not Found
    Python: 3.8.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

I'm new to react-native... Appreciate your help!

**Comment by romandr25** [comment]
This should do :))) 
https://www.youtube.com/watch?time_continue=9&v=N1I67FaluFE&feature=emb_logo
